version: "3.8"

x-attributes: &default-attributes
  stdin_open: true
  tty: true

services:
  app-chat-api:
    image: app-chat-api
    build: .
    restart: always
    <<: *default-attributes
    ports:
      - "8080:8080"
    environment:
        - WAIT_HOSTS=app-chat-db:27017
        - DB_HOST=app-chat-db
        - DB_PORT=27017
        - DB_NAME=app-chat-db
        - DB_USER=hcmut
        - DB_PASSWORD=hcmut123456

  app-chat-db:
    container_name: app-chat-db
    image: bitnami/mongodb:4.4.6-debian-10-r28
    ports:
      - "27017:27017"
    <<: *default-attributes
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=app-chat-db
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=hcmut123456
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=hcmut
      - MONGODB_PASSWORD=hcmut123456
      - MONGODB_DATABASE=app-chat-db
    volumes:
      - ./volumes/app-chat-db:/bitnami/mongodb

  app-chat-db-secondary:
    container_name: app-chat-db-secondary
    image: bitnami/mongodb:4.4.6-debian-10-r28
    <<: *default-attributes
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=app-chat-db-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=app-chat-db
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=hcmut123456
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - ./volumes/app-chat-db-secondary:/bitnami/mongodb
