name: publish

on:
  push:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/app-chat-api:latest
  ACTIONS_RUNNER_DEBUG: true

jobs:
    publish:
      name: publish image
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_DEV }}
          password: ${{ secrets.DOCKER_PASSWORD_DEV }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME_DEV }}/${{ github.event.repository.name }}:latest

    deploy:
        needs: publish
        name: deploy image
        runs-on: self-hosted

        steps:
        - name: pull and deploy
          run: |
            cd ${{ secrets.WORK_DIR }}
            docker compose pull
            docker compose up -d
            exit
